// Vietnamese text constants for the application

export const vi = {
  common: {
    search: "Tìm kiếm",
    viewDetails: "Xem chi tiết",
    bookNow: "Đặt lịch ngay",
    cancel: "Hủy",
    save: "Lưu",
    delete: "Xóa",
    edit: "Chỉnh sửa",
    add: "Thêm",
    back: "Quay lại",
    next: "Tiếp theo",
    confirm: "Xác nhận",
    close: "Đóng",
    submit: "Gửi",
    loading: "Đang tải...",
    noResults: "Không tìm thấy kết quả",
  },
  navigation: {
    home: "Trang chủ",
    search: "Tìm kiếm",
    bookings: "Lịch hẹn của tôi",
    profile: "Hồ sơ",
    dashboard: "Bảng điều khiển",
    settings: "Cài đặt",
    logout: "Đăng xuất",
    login: "Đăng nhập",
    register: "Đăng ký",
  },
  booking: {
    selectService: "Chọn dịch vụ",
    chooseStylist: "Chọn thợ",
    pickDateTime: "Chọn ngày & giờ",
    reviewConfirm: "Xem lại & Xác nhận",
    bookingSummary: "Tóm tắt đặt lịch",
    totalPrice: "Tổng giá",
    service: "Dịch vụ",
    stylist: "Thợ",
    date: "Ngày",
    time: "Giờ",
    duration: "Thời lượng",
    status: "Trạng thái",
  },
  salon: {
    featured: "Salon nổi bật",
    services: "Dịch vụ",
    stylists: "Thợ",
    reviews: "Đánh giá",
    address: "Địa chỉ",
    phone: "Số điện thoại",
    email: "Email",
    hours: "Giờ làm việc",
  },
}

